-- Create a table to store files generated by agents
create table if not exists agent_files (
  id bigint primary key generated always as identity,
  path text not null, -- Virtual path, e.g., "prd/main.md"
  content text, -- The content of the file
  agent_id text, -- Who created/updated it
  user_id uuid not null, -- The owner of the company
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  
  -- Ensure unique path per user
  unique(user_id, path)
);

-- Create a table to store tickets/tasks created by agents
create table if not exists agent_tickets (
  id bigint primary key generated always as identity,
  ticket_id text not null, -- The string ID e.g. "ticket_123"
  title text not null,
  description text,
  status text default 'open', -- open, in_progress, done
  priority text default 'medium',
  agent_id text,
  user_id uuid not null,
  created_at timestamp with time zone default now()
);

-- Enable RLS (Row Level Security)
alter table agent_files enable row level security;
alter table agent_tickets enable row level security;

-- Policies for agent_files
create policy "Users can view their own agent files"
on agent_files for select
using (auth.uid() = user_id);

create policy "Users can insert their own agent files"
on agent_files for insert
with check (auth.uid() = user_id);

create policy "Users can update their own agent files"
on agent_files for update
using (auth.uid() = user_id);

-- Policies for agent_tickets
create policy "Users can view their own agent tickets"
on agent_tickets for select
using (auth.uid() = user_id);

create policy "Users can insert their own agent tickets"
on agent_tickets for insert
with check (auth.uid() = user_id);

create policy "Users can update their own agent tickets"
on agent_tickets for update
using (auth.uid() = user_id);
