import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

serve(async (req) => {
    try {
        // 1. קבלת הנתונים מהבקשה (כמו שהמלצר רושם את ההזמנה)
        const { name } = await req.json()

        // 2. עיבוד (כמו שהטבח מכין את המנה)
        const data = {
            message: `Hello ${name || 'World'}!`,
            timestamp: new Date().toISOString(),
            explanation: "This response was generated by a server-side API function!"
        }

        // 3. החזרת התשובה (כמו שהמלצר מגיש את האוכל)
        return new Response(
            JSON.stringify(data),
            { headers: { "Content-Type": "application/json" } },
        )
    } catch (error) {
        return new Response(
            JSON.stringify({ error: "Failed to parse request body" }),
            { headers: { "Content-Type": "application/json" }, status: 400 },
        )
    }
})
