import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const YEAR = 2026;
const BASE_DIR = path.join(__dirname, '../planner', String(YEAR));

// Ensure directory exists
if (!fs.existsSync(BASE_DIR)) {
    fs.mkdirSync(BASE_DIR, { recursive: true });
}

// Current known high-level tasks to seed into "Today" (2026-01-16) and near future
const SEED_TASKS = [
    { date: '2026-01-16', tasks: ['Audit Service Providers', 'Verify Auto-Sync Pipeline'] },
    { date: '2026-01-17', tasks: ['Implement Vibe Token Analytics'] },
    { date: '2026-01-18', tasks: ['Optimize Mobile Booking Flow'] },
    { date: '2026-01-19', tasks: ['Security Audit: API Endpoints'] },
    { date: '2026-01-20', tasks: ['Content Review: Blog Posts'] }
];

function getMonthName(monthIndex) {
    const date = new Date(YEAR, monthIndex, 1);
    return date.toLocaleString('default', { month: 'long' });
}

function generateFiles() {
    const startDate = new Date(YEAR, 0, 1);
    const endDate = new Date(YEAR, 11, 31);

    let currentDate = startDate;

    while (currentDate <= endDate) {
        const month = String(currentDate.getMonth() + 1).padStart(2, '0');
        const day = String(currentDate.getDate()).padStart(2, '0');
        const dateStr = `${YEAR}-${month}-${day}`;
        const fileName = `${dateStr}.md`;
        const filePath = path.join(BASE_DIR, fileName);

        const monthName = getMonthName(currentDate.getMonth());

        // Check for seed tasks
        const seed = SEED_TASKS.find(t => t.date === dateStr);
        let taskSection = '';

        if (seed) {
            taskSection = seed.tasks.map(t => `- [ ] ${t} <!-- priority: high -->`).join('\n');
        } else {
            taskSection = '<!-- No specific tasks scheduled yet -->';
        }

        const content = `# 📑 Daily Protocol: ${dateStr}

## 🌅 Morning Boot Sequence (Logic Array)

> Standard operating procedure to ensure system integrity before starting new work.

- [ ] **🔍 System Integrity Check**: Verify all servers (Supabase, Node) are active.
- [ ] **🧪 Regression Scan**: Briefly test the last feature deployed yesterday.
- [ ] **🧹 Git Status**: Ensure local is synced (\`git pull\`) and clean.
- [ ] **🧠 Context Load**: Review yesterday's "Carry Over" and \`task.md\`.

## 🧠 Strategic Core & Task Distribution

> Head-Enlarging Strategy: How do we win today?

### 🎯 Primary Objective

> (One sentence goal for the day)

### 🧩 Task Breakdown & Agent Assignment

| Task ID | Description | Assigned Agent | Dependencies | Status |
| :---: | :--- | :---: | :--- | :--- |
| T-001 | [Auto-generated from Roadmap] | Tech Lead | None | ⏳ Pending |
| T-002 | ... | ... | ... | ... |

## 🤖 Agent Swarm Choreography

> Logic flow for multi-agent operations.

1. **Phase 1: Intelligence Gathering**
   - Agent: \`Research-Agent\` -> Scrape X, Analyze Y.
   - *Output*: Report stored in \`/docs/reports\`

2. **Phase 2: Execution**
   - Agent: \`Tech-Lead\` -> Implement code based on report.
   - *Trigger*: Completion of Phase 1.

## 🧬 Protocol Evolution (The "Upgrade Table")

> How did we improve the system today? (Meta-Improvement)

| 🕰️ Time | 💡 Improvement / Insight | 📉 Friction Reduced |
| :---: | :--- | :--- |
| --:-- | ... | ... |

## 🔮 Future Context Injection

> Items to push to future dates.

- [ ] ...

## 📝 Daily Log & Observations

-

---

> Generated by Protocol v2.0
`;

        // Only write if file doesn't exist to avoid overwriting user data if re-run (though for now we overwrite as requested)
        fs.writeFileSync(filePath, content);
        console.log(`Created: ${fileName}`);

        // Next Day
        currentDate.setDate(currentDate.getDate() + 1);
    }
}

generateFiles();
console.log(`\n✨ Successfully generated daily planner files for ${YEAR} in ${BASE_DIR}`);
