
import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import AgentProtocol from './lib/agent_protocol.js';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseServiceKey = process.env.VITE_SUPABASE_SERVICE_ROLE_KEY;
const supabase = createClient(supabaseUrl, supabaseServiceKey);
const protocol = new AgentProtocol('island_crawler');

async function simulate() {
    console.log("👻 Simulating 'Ghost Crawler' Event...");

    // 1. Create Mock Lead in DB
    const mockName = `Test Bar ${Math.floor(Math.random() * 1000)}`;
    const { data, error } = await supabase
        .from('service_providers')
        .insert({
            business_name: mockName,
            category: 'nightlife',
            location: 'Chaweng',
            verified: false,
            status: 'active',
            description: 'A simulation test bar generated by Cortex.'
        })
        .select()
        .single();

    if (error) {
        console.error("DB Error:", error);
        return;
    }
    console.log(`✅ Inserted Lead: ${mockName} (${data.id})`);

    // 2. Send Message to Sales
    protocol.sendMessage('sales_coordinator', 'lead_found', `
DB_ID: ${data.id}
New Lead Discovered: **${mockName}**
This is a simulated event for dashboard verification.
    `, { priority: 'high' });

    console.log("✅ Message sent to Sales Coordinator Inbox.");
}

simulate();
