import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const supabase = createClient(process.env.VITE_SUPABASE_URL, process.env.VITE_SUPABASE_SERVICE_ROLE_KEY);

async function testLeadFlow() {
    console.log("🤖 Starting Lead Flow Automation Test...");

    // 1. Snapshot current stats
    const { data: initialLeads, error: statsError } = await supabase
        .from('crm_leads')
        .select('tags');

    if (statsError) throw statsError;

    const countTag = (tag) => initialLeads.filter(l => l.tags && l.tags.includes(tag)).length;
    const initialTaxiCount = countTag('taxi');
    console.log(`📊 Initial Taxi Count: ${initialTaxiCount}`);

    // 2. Simulate User Action (New Taxi Lead)
    const fakeLead = {
        first_name: "Auto",
        last_name: `Test_${Date.now()}`,
        phone: "+66000000000",
        notes: "Generated by scripts/test_lead_flow.js",
        source: "landing_r_taxi",
        status: "new",
        tags: ["taxi", "smoke_test"] // "smoke_test" helps us identify test data later
    };

    console.log("📨 Inserting fake lead...");
    const { data: insertedLead, error: insertError } = await supabase
        .from('crm_leads')
        .insert(fakeLead)
        .select()
        .single();

    if (insertError) {
        console.error("❌ Insertion Failed:", insertError);
        process.exit(1);
    }
    console.log(`✅ Lead Created: ID ${insertedLead.id}`);

    // 3. Verify Stats Updated
    // Re-fetch to confirm aggregation logic works
    const { data: newLeads } = await supabase
        .from('crm_leads')
        .select('tags');

    const newTaxiCount = newLeads.filter(l => l.tags && l.tags.includes('taxi')).length;
    console.log(`📊 New Taxi Count: ${newTaxiCount}`);

    if (newTaxiCount === initialTaxiCount + 1) {
        console.log("✅ VERIFICATION PASSED: Dashboard will show update.");
    } else {
        console.error("❌ VERIFICATION FAILED: Count did not increment as expected.");
        process.exit(1);
    }
}

testLeadFlow();
