import { ToolRegistry } from "../ToolRegistry.js";

/**
 * A2UITools.js
 * Provides helper tools for Agents to generate rich A2UI components.
 * Agents can call these tools to get the correct JSON structure for charts, tables, etc.
 */

const createChartPayload = (type, data, config = {}) => {
    return {
        type: type,
        props: {
            data: data,
            dataKey: config.dataKey || "value",
            categories: config.categories || [],
            colors: config.colors,
            height: config.height || 300
        }
    };
};

// --- CHARTING TOOLS ---

ToolRegistry.register("generate_bar_chart", "Generate an A2UI Bar Chart component.", { data: "array", title: "string", description: "string", xKey: "string", categories: "array" }, async ({ data, title, description, xKey, categories }) => {
    // Input Validation
    if (!data || !Array.isArray(data)) return "[Error] 'data' must be an array of objects.";

    const chartNode = createChartPayload("bar-chart", data, {
        dataKey: xKey,
        categories: categories
    });

    const cardNode = {
        type: "card",
        props: {
            title: title || "Bar Chart",
            description: description || "Generated by Agent",
            content: chartNode
        }
    };

    return JSON.stringify(cardNode);
});

ToolRegistry.register("generate_line_chart", "Generate an A2UI Line Chart component.", { data: "array", title: "string", description: "string", xKey: "string", categories: "array" }, async ({ data, title, description, xKey, categories }) => {
    if (!data || !Array.isArray(data)) return "[Error] 'data' must be an array of objects.";

    const chartNode = createChartPayload("line-chart", data, {
        dataKey: xKey,
        categories: categories
    });

    const cardNode = {
        type: "card",
        props: {
            title: title || "Line Chart",
            description: description || "Generated by Agent",
            content: chartNode
        }
    };

    return JSON.stringify(cardNode);
});

ToolRegistry.register("generate_pie_chart", "Generate an A2UI Pie Chart component.", { data: "array", title: "string", description: "string", nameKey: "string", valueKey: "string" }, async ({ data, title, description, nameKey, valueKey }) => {
    if (!data || !Array.isArray(data)) return "[Error] 'data' must be an array of objects.";

    const chartNode = createChartPayload("pie-chart", data, {
        dataKey: valueKey || "value",
        categories: [], // Pie chart doesn't use categories same way
        nameKey: nameKey || "name"
    });
    // Pie chart specific prop fix if needed in createChartPayload, but A2UI Renderer handles it.
    // Actually createChartPayload passes 'dataKey' which renderer uses.

    const cardNode = {
        type: "card",
        props: {
            title: title || "Pie Chart",
            description: description || "Generated by Agent",
            content: {
                ...chartNode,
                props: { ...chartNode.props, nameKey: nameKey || "name" }
            }
        }
    };

    return JSON.stringify(cardNode);
});

// --- DATA TOOLS ---

ToolRegistry.register("generate_data_table", "Generate an A2UI Data Table component.", { headers: "array", rows: "array", title: "string", caption: "string" }, async ({ headers, rows, title, caption }) => {
    if (!headers || !rows) return "[Error] 'headers' (array) and 'rows' (array of arrays) are required.";

    const tableNode = {
        type: "data-table",
        props: {
            headers,
            rows,
            caption
        }
    };

    if (title) {
        return JSON.stringify({
            type: "card",
            props: {
                title: title,
                content: tableNode
            }
        });
    }

    return JSON.stringify(tableNode);
});

ToolRegistry.register("generate_dashboard_view", "Generate a full A2UI Dashboard layout.", { stats: "array", charts: "array" }, async ({ stats, charts }) => {
    // Helper to generate a full dashboard layout
    // Stats: Array of { title, value, icon, change, trend }
    // Charts: Array of { type, data, ... } (Usually simplified refs or full objects)

    // This tool is complex, let's keep it simple for now.
    // It returns a container with a row of stats and then rows of charts.

    const statCards = (stats || []).map(stat => ({
        type: "stat-card",
        props: stat
    }));

    const statRow = {
        type: "row",
        props: { className: "grid gap-4 md:grid-cols-2 lg:grid-cols-4" },
        children: statCards
    };

    // For simplicity, just returning the stats row and a placeholder for charts if provided
    return JSON.stringify({
        type: "container",
        props: { className: "space-y-4" },
        children: [statRow]
    });
});
