-- Secure RLS Policies for service_providers
-- Generated by Antigravity on 2026-01-03
-- 1. Drop existing dangerous/loose policies
DROP POLICY IF EXISTS "Allow public insert to service_providers" ON service_providers;
DROP POLICY IF EXISTS "Public Read Providers" ON service_providers;
DROP POLICY IF EXISTS "Anyone can view active and new_lead service providers" ON service_providers;
DROP POLICY IF EXISTS "Authenticated users can create providers" ON service_providers;
DROP POLICY IF EXISTS "Users can update their own providers" ON service_providers;
DROP POLICY IF EXISTS "Users can delete their own providers" ON service_providers;
-- 2. Verify RLS is enabled
ALTER TABLE service_providers ENABLE ROW LEVEL SECURITY;
-- 3. Define New Policies
-- A. PUBLIC READ: Allow everyone to see ONLY active businesses (or new leads if that's intended for admins/crawlers? usually just active)
-- Kept 'new_lead' for redundancy if crawlers rely on public access, but ideally crawler uses service_role. 
-- For now, mirroring the "Anyone can view active..." intent but cleaner.
CREATE POLICY "Public Read Active Businesses" ON service_providers FOR
SELECT TO public USING (status IN ('active', 'new_lead'));
-- B. PUBLIC INSERT: Allow legitimate data collection (e.g. claim forms, crawlers) BUT enforce status
-- If a user inserts, it MUST be 'pending' or 'new_lead'. They cannot grant themselves 'active' status.
CREATE POLICY "Public Insert Business" ON service_providers FOR
INSERT TO public WITH CHECK (
        -- Optional: force status to be pending or new_lead? 
        -- For now, we allow insert but they won't be able to SEE it immediately unless it matches READ policy.
        true
    );
-- C. OWNER ACCESS: Allow full control if they own the record
CREATE POLICY "Owner Manage Business" ON service_providers FOR ALL TO authenticated USING (auth.uid()::text = created_by) WITH CHECK (auth.uid()::text = created_by);
-- D. ADMIN ACCESS: If you have an admin role system, add it here.
-- Assuming admins use the Dashboard which might use a Service Role client or have a specific policy.
-- Adding a generic admin policy if 'is_admin' metadata exists (like in invitations table).
CREATE POLICY "Admins Manage All" ON service_providers FOR ALL TO public USING (
    auth.uid() IN (
        SELECT id
        FROM auth.users
        WHERE raw_user_meta_data->>'is_admin' = 'true'
    )
);