-- Create posts table for the Blog
CREATE TABLE public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    content TEXT,
    -- Could be Markdown or HTML
    excerpt TEXT,
    cover_image TEXT,
    tags TEXT [],
    -- Array of strings for tags
    published BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMPTZ,
    author_id UUID REFERENCES auth.users(id)
);
-- Create events table
CREATE TABLE public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ,
    location_name TEXT,
    location_lat FLOAT,
    location_lng FLOAT,
    source_url TEXT,
    -- Where this event was scraped from
    category TEXT,
    is_verified BOOLEAN DEFAULT FALSE
);
-- Create faqs table
CREATE TABLE public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT,
    popularity_score INT DEFAULT 0,
    is_published BOOLEAN DEFAULT TRUE
);
-- Enable RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
-- Policies for POSTS
-- Everyone can read published posts
CREATE POLICY "Public can view published posts" ON public.posts FOR
SELECT USING (published = true);
-- Authenticated users (admins/agents) can do everything
CREATE POLICY "Admins can manage posts" ON public.posts FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- Policies for EVENTS
-- Everyone can read verified events (or all, depending on strategy. Let's say all for now)
CREATE POLICY "Public can view events" ON public.events FOR
SELECT USING (true);
-- Authenticated can manage
CREATE POLICY "Admins can manage events" ON public.events FOR ALL TO authenticated USING (true) WITH CHECK (true);
-- Policies for FAQS
-- Everyone can read published FAQs
CREATE POLICY "Public can view published faqs" ON public.faqs FOR
SELECT USING (is_published = true);
-- Authenticated can manage
CREATE POLICY "Admins can manage faqs" ON public.faqs FOR ALL TO authenticated USING (true) WITH CHECK (true);